inputFilePath: "/Users/rudaks/temp/custom2docx"
inputFileExtension: "docx"
outputFilePath: "/Users/rudaks/temp/output"

writeToExcel: true
writeToDb: true
compareFileExistWithSvn: true

excelColumns:
  - { id: "customizeName", columnName: "커스트마이징 명칭", autoSize: true, addColumnWidth: 0 }
  - { id: "requirements", columnName: "요구사항", autoSize: false, addColumnWidth: 8400, mapToWordParagraph: "고객요구사항,프로세스 설명" }
  - { id: "javaChanges", columnName: "java 변경사항", autoSize: false, addColumnWidth: 8400, mapToWordParagraph: "상세 구현 내용" }
  - { id: "dbChanges", columnName: "DB 변경사항", autoSize: false, addColumnWidth: 8400, mapToWordParagraph: "테이블 변경" }
  - { id: "changedFiles", columnName: "변경 파일", autoSize: false, addColumnWidth: 8400, mapToWordParagraph: "패키지 경로" }
  - { id: "customizeType", columnName: "커스터마이징 타입", autoSize: false, addColumnWidth: 0 }
  - { id: "changedService", columnName: "변경 서비스", autoSize: false, addColumnWidth: 0 }
  - { id: "developer", columnName: "작업자", autoSize: false, addColumnWidth: 0, mapToWordParagraph: "수정자" }
  - { id: "solution", columnName: "해결방안", autoSize: false, addColumnWidth: 0 }
  - { id: "cause", columnName: "이유", autoSize: false, addColumnWidth: 0 }


jdbcDriver: "org.postgresql.Driver"
jdbcUrl: "jdbc:postgresql://127.0.0.1:5432/testdb"
jdbcUser: "test"
jdbcPassword: "test"

svnPath: "/Users/rudaks/_WORK/_SVN/SuperTalk/eer/tags"