server:
  port: 8000

spring:
  application:
    name: zuul-gateway
  devtools:
    restart:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8010/eureka

management:
  endpoints:
    web:
      exposure:
        include: '*'

api:
  zuul:
    actuator:
      url:
        path: /actuator/*